const mongoose=require('mongoose')

const astroLogerSchema=new mongoose.Schema({
    astroName:{
        type:String,
        require:true,
        default:null,
    },
    astroDob:{
        type:String,
        require:true,
        default:null,
    },
    mobile:{
        type:Number,
        require:true,
        unique:true,
    },
    email:{
        type:String,
        require:true,
        default:null,
    },
    password:{
        type:String,
        require:true,
        default:null,        
    },
    city:{
        type:String,
        require:true,
        default:null,
    },
    profileImg:{
        type:String,
        default:null,        
    },
    experience:{
        type:String,
        default:0,        
    },
    expertise:{
        type:String,
        require:true,
        default:null,
    },
    langauge:{
        type:String,
        default:"Hindi",
        require:true,
    },
    shortBio:{
        type:String,
        default:null,
    },
    chargePerSession:{
        type:String,
        default:null,
    },
    availableTime:{
        type:String,
        default:null,
    },
    verifyDocument:{
        type:String,
        default:null,
    },
    bankDetails:{
        type:String,
        default:null
    }
   
},{
    timeseries:true,
});

const astrologer_schema=mongoose.model('Astrologer',astroLogerSchema);
module.exports=astrologer_schema;